# Generated by Django 5.0.4 on 2024-05-01 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_shops_latitude_shops_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shops',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='shops',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
    ]
