# Generated by Django 5.0.4 on 2024-05-01 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0006_alter_shops_latitude_alter_shops_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shops',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='shops',
            name='longitude',
        ),
    ]
