# Generated by Django 5.0.4 on 2024-04-17 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordershop',
            name='packet_picked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordershop',
            name='payment_received',
            field=models.BooleanField(default=False),
        ),
    ]
