# Generated by Django 5.0.4 on 2024-04-17 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_ordershop_packet_picked_ordershop_payment_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='Pending', max_length=255),
        ),
    ]
