# Generated by Django 5.0.4 on 2024-05-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderproduct_product_name_ordershop_shop_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CacheData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(max_length=255, unique=True)),
                ('distance_value', models.FloatField()),
            ],
        ),
    ]
